#!/bin/sh
## Add this file in .git/hooks to be runned before every commit,
## (you need to have package.json configured to run tests)

#STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "js$")

npm test
if [ "$?"==0 ]; then
    echo "\t\033[32mJest Tests Passed\033[0m"
    exit 0
else
    echo "\t\033[41mJest Tests Failed\033[0m"
    #PASS=false
    exit 1
fi
